# Generated by Django 5.2 on 2025-04-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='provider_video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
