# Generated by Django 5.2 on 2025-04-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_dislikes_video_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
