# Generated by Django 5.2 on 2025-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
