# Generated by Django 5.2 on 2025-04-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='popularity',
        ),
    ]
