# Generated by Django 5.2 on 2025-04-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_video_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
